apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: neolab-dev
image: docker.io/rancher/k3s:v1.30.2-k3s2
servers: 1
agents: 0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable-helm-controller
        nodeFilters:
          - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 51820:51820
    nodeFilters:
      - loadbalancer
registries:
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - http://docker-io:5000
